IntegrationMSZ/Models/OwnModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Web;

namespace IntegrationMSZ.Models
{
    public class Signature
    {
        public string SignatureText { get; set; }
    }

    public class ApplicationModel
    {
        [DisplayName("Topic")]
        public string topic { get; set; }
        [DisplayName("Topic")]
        public int type { get; set; }
        [DisplayName("Start Datetime")]
        public DateTime start_time { get; set; }
        [DisplayName("Duration")]
        public int duration { get; set; }
        [DisplayName("Duration")]
        public Settings settings { get; set; }
    }

    public class ScheduleMeetingModel
    {
        public string id { get; set; }
        public string password { get; set; }
        public string topic { get; set; }
        public string start_time { get; set; }
        public string duration { get; set; }
        public string join_url { get; set; } 
    }
    public class Settings
    {
        public bool host_video { get; set; }
        public bool participant_video { get; set; }
        public bool cn_meeting { get; set; }
        public bool in_meeting { get; set; }
        public bool join_before_host { get; set; }
        public bool mute_upon_entry { get; set; } = false;
        public string audio { get; set; }
        public bool registrants_email_notification { get; set; }

    }
}

IntegrationMSZ/Controllers/HomeController.cs
using IntegrationMSZ.Models;
using Microsoft.IdentityModel.Tokens;
using RestSharp;
using System;
using System.Collections.Generic;
using System.IdentityModel.Tokens.Jwt;
using System.Linq;
using System.Security.Claims;
using System.Security.Cryptography;
using System.Text;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace IntegrationMSZ.Controllers
{
    public class HomeController : Controller
    {

        public ActionResult Index()
        {
            return View(new ApplicationModel());
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

IntegrationMSZ/Controllers/StartZoomController.cs
using IntegrationMSZ.Models;
using Microsoft.IdentityModel.Tokens;
using Newtonsoft.Json;
using RestSharp;
using System;
using System.Collections.Generic;
using System.IdentityModel.Tokens.Jwt;
using System.Linq;
using System.Security.Claims;
using System.Security.Cryptography;
using System.Text;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace IntegrationMSZ.Controllers
{
    public class StartZoomController : Controller
    {
        protected string ApiKey = System.Configuration.ConfigurationManager.AppSettings["apiKey"];
        protected string ApiSecret = System.Configuration.ConfigurationManager.AppSettings["apiSecret"];
        protected string JwtKey = System.Configuration.ConfigurationManager.AppSettings["jwtKey"];
        protected string JwtSecret = System.Configuration.ConfigurationManager.AppSettings["jwtSecret"];
        protected string Redirect_uri = "";
        protected string UserName = System.Configuration.ConfigurationManager.AppSettings["user_name"];

        public ActionResult Index()
        {
            var ApplicationModel = new ApplicationModel();
            ApplicationModel.type = 2;
            return View(ApplicationModel);
        }
         
        /// <summary>
        /// Create and Join meeting: 
        /// </summary>
        /// <param name="application"></param>        
        /// <returns>Meeting detail</returns>
        [HttpPost]
        public ActionResult CreateaMeeting(ApplicationModel application)
        {
            application.settings = new Settings()
            {
                host_video = true,
                participant_video = true,
                join_before_host = false,
                mute_upon_entry = false,
                audio = "both",
                registrants_email_notification = true
            };

            string uri = string.Format("https://api.zoom.us");
            var client = new RestClient(uri);
            var request = new RestRequest("v2/users/me/meetings", Method.Post);

            request.RequestFormat = DataFormat.Json;
            request.AddJsonBody(new { topic = application.topic, duration = application.duration, start_time = application.start_time, type = application.type });
            //request.AddJsonBody(new { topic = "Meeting with Ussain", duration = "10", start_time = DateTime.Now.AddHours(1), type = "2" });
            request.AddHeader("authorization", String.Format("Bearer {0}", GenerateAccessToken()));
            var restResponse = Task.Run(() => client.ExecuteAsync(request)).Result;

            var response = Newtonsoft.Json.JsonConvert.DeserializeObject<ScheduleMeetingModel>(restResponse.Content);
            
            return RedirectToAction("ScheduleMeeting",response);
        }
        public ActionResult ScheduleMeeting(ScheduleMeetingModel meeting) 
        {
            return View(meeting);
        }
        public ActionResult Student() 
        {
            return View();
        }
        /// <summary>
        /// Generate Signature for base64Salth before start meeting.
        /// Role : 1 -> (Teacher) Create meeting , 0 -> (Student) Join meeting
        /// </summary>
        /// <param name="meetingNumber"></param>
        /// <param name="role"></param>
        /// <returns>Signature</returns>
        [HttpGet]
        public ActionResult GenerateSignature(string meetingNumber, string role)
        {

            char[] padding = { '=' };
            string apiKey = JwtKey;
            string apiSecret = JwtSecret;
            String ts = (ToTimestamp(DateTime.UtcNow.ToUniversalTime()) - 30000).ToString();

            string message = String.Format("{0}{1}{2}{3}", apiKey, meetingNumber, ts, role);
            apiSecret = apiSecret ?? "";
            var encoding = new System.Text.ASCIIEncoding();
            byte[] keyByte = encoding.GetBytes(apiSecret);
            byte[] messageBytesTest = encoding.GetBytes(message);
            string msgHashPreHmac = System.Convert.ToBase64String(messageBytesTest);
            byte[] messageBytes = encoding.GetBytes(msgHashPreHmac);
            using (var hmacsha256 = new HMACSHA256(keyByte))
            {
                byte[] hashmessage = hmacsha256.ComputeHash(messageBytes);
                string msgHash = System.Convert.ToBase64String(hashmessage);
                string token = String.Format("{0}.{1}.{2}.{3}.{4}", apiKey, meetingNumber, ts, role, msgHash);
                var tokenBytes = System.Text.Encoding.UTF8.GetBytes(token);
                var sig = new Signature()
                {
                    SignatureText = System.Convert.ToBase64String(tokenBytes).TrimEnd(padding)
                };
                List<string> vals = new List<string>();
                vals.Add(JwtKey);
                vals.Add(sig.SignatureText);
                return this.Json(vals, JsonRequestBehavior.AllowGet);
            }           
        }
        long ToTimestamp(DateTime value)
        {
            long epoch = (value.Ticks - 621355968000000000) / 10000;
            return epoch;
        }
        private object GenerateAccessToken()
        {
            var signinkey = new SymmetricSecurityKey(Encoding.UTF8.GetBytes(JwtSecret));

            var claims = new List<Claim> { new Claim("username", UserName) };
            claims.Add(new Claim("userid", UserName));
            //claims.Add(new Claim("tenantid", _configuration["Tenant:TenantId"]));

            var token = new JwtSecurityToken(
                issuer: JwtKey,
                audience: Redirect_uri,
                claims: claims,
                expires: DateTime.UtcNow.AddMinutes(90),
                signingCredentials: new SigningCredentials(signinkey, SecurityAlgorithms.HmacSha256)
                );
            return new JwtSecurityTokenHandler().WriteToken(token);
        }

      
    }
}

IntegrationMSZ/Controllers/ZoomJoinController.cs
using IntegrationMSZ.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace IntegrationMSZ.Controllers
{
    public class ZoomJoinController : Controller
    {
        // GET: ZoomJoin
        public ActionResult Index(ApplicationModel model)
        {
            model.type = 1;
            return View(model);
        }
    }
}

IntegrationMSZ/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

IntegrationMSZ/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

IntegrationMSZ/Views/Home/Index.cshtml
@model IntegrationMSZ.Models.ApplicationModel
@{
    ViewBag.Title = "Home Page";
   

}

<h1>home</h1>

IntegrationMSZ/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Video Conferencing Application</title>

    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    


</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("Teacher", "Index", "StartZoom")</li>
                    <li>@Html.ActionLink("Student", "Student", "StartZoom")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Video Conferencing Application</p>
        </footer>
    </div>
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    
    @RenderSection("scripts", required: false)
</body>
</html>

IntegrationMSZ/Views/StartZoom/Index.cshtml
@model IntegrationMSZ.Models.ApplicationModel

@{
    ViewBag.Title = "Schedule Zoom Meeting";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@using (Html.BeginForm("CreateaMeeting", "StartZoom", FormMethod.Post))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Create Meeting</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.topic, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.topic, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.topic, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.start_time, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.start_time, new { htmlAttributes = new { @class = "form-control", Type = "datetime-local" } })
                @Html.ValidationMessageFor(model => model.start_time, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.duration, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.HiddenFor(model => model.type)  
                @Html.EditorFor(model => model.duration, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.duration, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

IntegrationMSZ/Views/StartZoom/ScheduleMeeting.cshtml
@model IntegrationMSZ.Models.ScheduleMeetingModel


@{
    ViewBag.Title = "Home Page";

}
    <!-- For Client View -->
    <link type="text/css" rel="stylesheet" href="https://source.zoom.us/2.3.0/css/bootstrap.css" />
    <link type="text/css" rel="stylesheet" href="https://source.zoom.us/2.3.0/css/react-select.css" />
    <link href="~/Scripts/file/styles.css" rel="stylesheet" />

   
    <div>
        <h4>ScheduleMeetingModel</h4>
        <hr />
        <dl class="dl-horizontal">
            <dt>
                @Html.DisplayNameFor(model => model.topic)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.topic)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.id)
            </dt>

            <dd id="id">
                @Html.DisplayFor(model => model.id)
            </dd>
            <dt style="display:none">
                @Html.DisplayNameFor(model => model.password)
            </dt>

            <dd style="display:none" id="password">
                @Html.DisplayFor(model => model.password)
            </dd>



            <dt>
                @Html.DisplayNameFor(model => model.start_time)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.start_time)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.duration)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.duration)
            </dd>

            @*<dd>
                    @Html.Action(model => model.join_url)
                </dd>
                <dd>Or</dd>*@
        </dl>
    </div>

    <main>
        <h1>Zoom Meeting</h1>

        <!-- For Component View -->
        <div id="meetingSDKElement">
            <!-- Zoom Meeting SDK Rendered Here -->
        </div>

        <button onClick="getSignature(1)">Start Meeting</button>
    </main>

    <!-- For Component and Client View -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.0/jquery.min.js" integrity="sha512-894YE6QWD5I59HgZOGReFYm4dnWc1Qt5NtvYSaNcOP+u1T9qYdvdihz0PPSiiqn/+/3e7Jo4EaG7TubfWGUrMQ==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>

    <script src="https://source.zoom.us/2.3.0/lib/vendor/react.min.js"></script>
    <script src="https://source.zoom.us/2.3.0/lib/vendor/react-dom.min.js"></script>
    <script src="https://source.zoom.us/2.3.0/lib/vendor/redux.min.js"></script>
    <script src="https://source.zoom.us/2.3.0/lib/vendor/redux-thunk.min.js"></script>
    <script src="https://source.zoom.us/2.3.0/lib/vendor/lodash.min.js"></script>

    <!-- For Client View -->
    <script src="https://source.zoom.us/zoom-meeting-2.3.0.min.js"></script>
    <script src="~/Scripts/file/client-view.js"></script>

IntegrationMSZ/Views/StartZoom/Student.cshtml
@{
    ViewBag.Title = "Student Page";

}
<h2>ScheduleMeeting</h2>



    <!-- For Client View -->
    <link type="text/css" rel="stylesheet" href="https://source.zoom.us/2.3.0/css/bootstrap.css" />
    <link type="text/css" rel="stylesheet" href="https://source.zoom.us/2.3.0/css/react-select.css" />
    <link href="~/Scripts/file/styles.css" rel="stylesheet" />
  

    <main>
        
        <div id="meetingSDKElement">
            <!-- Zoom Meeting SDK Rendered Here -->
        </div>
        <div>

            <h1>Student Meeting</h1>
            <label>Name</label>
            <input type="text" id="name" class="form-control" style="margin:auto" />
            <label>Meeting Id</label>
            <input type="text" id="id" class="form-control" style="margin:auto" />
            <label style="display:none">Password</label>
            <input style="display:none" type="text" id="password" class="form-control" style="margin:auto" />
        </div>
        <button onClick="getSignature(0)">Join Meeting</button>
    </main>

    <!-- For Component and Client View -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.0/jquery.min.js" integrity="sha512-894YE6QWD5I59HgZOGReFYm4dnWc1Qt5NtvYSaNcOP+u1T9qYdvdihz0PPSiiqn/+/3e7Jo4EaG7TubfWGUrMQ==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>

    <script src="https://source.zoom.us/2.3.0/lib/vendor/react.min.js"></script>
    <script src="https://source.zoom.us/2.3.0/lib/vendor/react-dom.min.js"></script>
    <script src="https://source.zoom.us/2.3.0/lib/vendor/redux.min.js"></script>
    <script src="https://source.zoom.us/2.3.0/lib/vendor/redux-thunk.min.js"></script>
    <script src="https://source.zoom.us/2.3.0/lib/vendor/lodash.min.js"></script>
    <!-- For Client View -->
    <script src="https://source.zoom.us/zoom-meeting-2.3.0.min.js"></script>
    <script src="~/Scripts/file/client-view.js"></script>

IntegrationMSZ/Views/ZoomJoin/Index.cshtml
@model IntegrationMSZ.Models.ApplicationModel

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Index</h2>

<div>
    <h4>ApplicationModel</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.topic)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.topic)
        </dd>
        
        <dt>
            @Html.DisplayNameFor(model => model.start_time)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.start_time)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.duration)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.duration)
            @Html.HiddenFor(model => model.type)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { /* id = Model.PrimaryKey */ }) |
    @Html.ActionLink("Back to List", "Index")
</p>